export const styles = {
  section: { marginTop: '1.5rem', paddingTop: '1.5rem', borderTop: '1px solid #e5e7eb', maxWidth: 480 },
  heading: { fontSize: '1rem' },
  checkboxRow: { display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.9rem' },
  daemonBlock: { marginTop: '1rem' },
  hint: { fontSize: '0.85rem', color: '#4b5563', marginBottom: 8 },
  fieldLabel: { display: 'block', fontSize: '0.85rem', marginBottom: 8 },
  input: { display: 'block', width: '100%', marginTop: 2, boxSizing: 'border-box' } as const,
  thresholdRow: { display: 'flex', gap: '1rem' },
  thresholdField: { flex: 1, display: 'block', fontSize: '0.85rem' },
  ok: { color: '#16a34a', marginLeft: 8, fontSize: '0.85rem' },
  error: { color: '#dc2626', marginLeft: 8, fontSize: '0.85rem' },
  pairingRow: { display: 'flex', alignItems: 'center', gap: 8, fontSize: '0.9rem', marginBottom: 4 },
  pairingDot: { fontSize: '0.7rem' },
  advanced: { marginTop: '0.75rem' },
  advancedSummary: { fontSize: '0.85rem', color: '#4b5563', cursor: 'pointer' },
  checklist: { listStyle: 'none', padding: 0, margin: '0.5rem 0 0' },
  checklistItem: { fontSize: '0.85rem', marginBottom: 4 },
  checklistDone: { color: '#16a34a' },
  checklistPending: { color: '#6b7280' },
  backupRow: { display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
  restorePreview: { marginTop: 8, padding: '0.75rem', border: '1px solid #e5e7eb', borderRadius: 6, fontSize: '0.85rem', maxWidth: 480 },
} as const;
